name: Update GitHub Activity

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    name: Update recent activity

    steps:
      - name: Update GitHub profile activity
        uses: Readme-Workflows/recent-activity@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          GH_USERNAME: refuse-wrong
          CONFIG_FILE: .github/recent-activity.config.yml
